using System.Diagnostics.CodeAnalysis;
using SapphireGuard.ModelHarness.Framework.State;

namespace SapphireGuard.ModelHarness.Framework.Guides;

/// <summary>
/// Appends harness-level instructions to the system prompt so the model understands
/// what sensor observation notes mean and how to respond to them.
/// </summary>
[ExcludeFromCodeCoverage]
public sealed class HarnessInstructionsGuide : IGuide
{
    public string Name => "harness-instructions";

    private const string Instructions = """


        ## Harness observations

        During your execution the harness may append notes formatted as [HARNESS OBSERVATION — ...].
        These are sensor findings generated by the system — not user messages and not part of your task context.
        When you see one:
        - Treat it as a directive, not as optional context.
        - Acknowledge the concern and adjust your next action accordingly.
        - Do not repeat behaviour that has already been flagged.
        """;

    public Task ContributeAsync(ContextDraft draft, AgentState state, CancellationToken ct)
    {
        draft.SystemPrompt += Instructions;
        return Task.CompletedTask;
    }
}
